# Generated by Django 3.2.25 on 2024-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReturnFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='home/files')),
            ],
            options={
                'verbose_name': 'Annual Return Files',
                'verbose_name_plural': 'Annual Return Files',
            },
        ),
        migrations.CreateModel(
            name='AreasOfSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Areas Of Support',
                'verbose_name_plural': 'Areas Of Support',
            },
        ),
        migrations.CreateModel(
            name='CsrPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='home/files')),
            ],
            options={
                'verbose_name': 'CSR Policy',
                'verbose_name_plural': 'CSR Policy',
            },
        ),
        migrations.CreateModel(
            name='OgqImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('caption', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Olympic Impact Players',
                'verbose_name_plural': 'Olympic Impact Players',
            },
        ),
        migrations.CreateModel(
            name='Olympic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('archery', 'archery'), ('athletics', 'athletics'), ('badminton', 'badminton'), ('boxing', 'boxing'), ('shooting', 'shooting'), ('table tenis', 'table tenis'), ('weightlifting', 'weightlifting'), ('wrestling', 'wrestling'), ('junior scholorship athletes', 'junior scholorship athletes')], max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('event', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='OlympicResultPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('rio 2016', 'rio 2016'), ('london 2012', 'london 2012')], max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('caption', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Olympic Results Players',
                'verbose_name_plural': 'Olympic Results Players',
            },
        ),
        migrations.CreateModel(
            name='Paralympic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('archery', 'archery'), ('athletics', 'athletics'), ('badminton', 'badminton'), ('canoe', 'canoe'), ('judo', 'judo'), ('power lifting', 'power lifting'), ('shooting', 'shooting'), ('table tenis', 'table tenis')], max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('event', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='home/files')),
            ],
            options={
                'verbose_name': 'Performance Report Files',
                'verbose_name_plural': 'Performance Report Files',
            },
        ),
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Selection Process',
                'verbose_name_plural': 'Selection Process',
            },
        ),
        migrations.CreateModel(
            name='TeamOgq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('US', 'US'), ('IN', 'IN')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('joining_date', models.DateField(auto_now=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('sporting_achivements', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vision And Mission',
                'verbose_name_plural': 'Vision And Mission',
            },
        ),
        migrations.DeleteModel(
            name='Careers',
        ),
        migrations.DeleteModel(
            name='MediaArticle',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name2',
        ),
    ]
