# Generated by Django 3.2.25 on 2024-06-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240615_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Home Page Carousel',
                'verbose_name_plural': 'Home Page Carousel',
            },
        ),
        migrations.CreateModel(
            name='JuniorAthletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('archery', 'archery'), ('athletics', 'athletics'), ('badminton', 'badminton'), ('boxing', 'boxing'), ('shooting', 'shooting'), ('table tennis', 'table tennis'), ('wrestling', 'wrestling')], max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('event', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Junior Scholoarship athletes',
                'verbose_name_plural': 'Junior Scholoarship athletes',
            },
        ),
        migrations.CreateModel(
            name='TeamOgqIndia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('joining_date', models.DateField(auto_now=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('sporting_achivements', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team OGQ India',
                'verbose_name_plural': 'Team OGQ India',
            },
        ),
        migrations.CreateModel(
            name='TeamOgqUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('joining_date', models.DateField(auto_now=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('sporting_achivements', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team OGQ US',
                'verbose_name_plural': 'Team OGQ US',
            },
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='TeamOgq',
        ),
        migrations.RenameField(
            model_name='olympicresultplayers',
            old_name='sport',
            new_name='olympic_year',
        ),
        migrations.AlterField(
            model_name='olympic',
            name='sport',
            field=models.CharField(blank=True, choices=[('archery', 'archery'), ('athletics', 'athletics'), ('badminton', 'badminton'), ('boxing', 'boxing'), ('shooting', 'shooting'), ('table tennis', 'table tennis'), ('weightlifting', 'weightlifting'), ('wrestling', 'wrestling')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paralympic',
            name='sport',
            field=models.CharField(blank=True, choices=[('archery', 'archery'), ('athletics', 'athletics'), ('badminton', 'badminton'), ('canoe', 'canoe'), ('judo', 'judo'), ('power lifting', 'power lifting'), ('shooting', 'shooting'), ('table tennis', 'table tennis')], max_length=100, null=True),
        ),
    ]
