# Generated by Django 3.2.25 on 2024-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240622_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogqimpact',
            name='about_them',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamogqindia',
            name='group',
            field=models.CharField(blank=True, choices=[('paris 2024', 'paris 2024'), ('rio 2016', 'rio 2016'), ('london 2012', 'london 2012')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='olympicresultplayers',
            name='olympic_year',
            field=models.CharField(blank=True, choices=[('paris 2024', 'paris 2024'), ('rio 2016', 'rio 2016'), ('london 2012', 'london 2012')], max_length=100, null=True),
        ),
    ]
