# Generated by Django 3.2.25 on 2024-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240707_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympicNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Add olympics',
                'verbose_name_plural': 'Add olympics',
            },
        ),
        migrations.CreateModel(
            name='SportsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Sport options',
                'verbose_name_plural': 'Sport options',
            },
        ),
        migrations.CreateModel(
            name='TeamPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Team Position options',
                'verbose_name_plural': 'Team Position options',
            },
        ),
        migrations.AlterField(
            model_name='teamogqindia',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
