# Generated by Django 3.2.25 on 2024-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240712_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countdown',
            old_name='content',
            new_name='extra_info',
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='content',
            new_name='extra_info',
        ),
        migrations.AddField(
            model_name='teamogqindia',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
