# Generated by Django 3.2.25 on 2024-07-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20240714_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='extra_info',
        ),
        migrations.AlterField(
            model_name='countdown',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
