# Generated by Django 3.2.25 on 2024-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20240721_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParalympicResultPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympic_year', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('caption', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('rank', models.BigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Paralympic Results Players',
                'verbose_name_plural': 'Paralympic Results Players',
            },
        ),
        migrations.AddField(
            model_name='juniorathletes',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ogqimpact',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olympic',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='olympicresultplayers',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paralympic',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamogqus',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='rank',
            field=models.BigIntegerField(default=1),
        ),
    ]
